// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// cs_out //
// ------ //

#define cs_out_wrap_target 0
#define cs_out_wrap 1
#define cs_out_pio_version 1

static const uint16_t cs_out_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0x6004, //  1: out    pins, 4
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program cs_out_program = {
    .instructions = cs_out_program_instructions,
    .length = 2,
    .origin = -1,
    .pio_version = cs_out_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config cs_out_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + cs_out_wrap_target, offset + cs_out_wrap);
    return c;
}

static inline void cs_out_program_init(PIO pio, uint sm, uint offset, uint base_pin) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_out_pins(&c, base_pin, 4);
    sm_config_set_out_shift(&c, true, true, 32);
    sm_config_set_wrap(&c, offset, offset + 1);
    for (int i = 0; i < 4; i++) {
        pio_gpio_init(pio, base_pin + i);
    }
    pio_sm_set_consecutive_pindirs(pio, sm, base_pin, 4, true);
    pio_sm_set_pins_with_mask(pio, sm,
        (uint32_t)0x0F << base_pin,
        0x0Fu << base_pin);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

